import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import FooterHandler from "@/components/FooterHandler";
import { ClerkProvider } from "@clerk/nextjs";


// Google Font
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Car Rental",
  description: "Generated by Muniza Nabeel",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
     <html lang="en">
        <body className={`${plusJakartaSans.variable}`}>
        
            <Navbar />
            <main>{children}</main>        
            <FooterHandler />
        </body>
      </html>
    </ClerkProvider>
  );
}